<?php

declare(strict_types=1);

namespace App\Tenant\Signup;

use App\Platform\Tenancy\TenantContext;

/**
 * Estimates how likely a new email-list signup is spam/abuse, using only
 * signals available at signup time (no outbound network calls, so this never
 * adds latency or a new failure mode to the public signup/import path).
 *
 * This is a deterministic heuristic, not a machine-learning classifier: each
 * matched signal adds a fixed weight, capped at 100. It is intentionally
 * conservative (favors false negatives over blocking real subscribers) since
 * the result is only ever shown to a human admin, not used to auto-reject.
 */
final class SpamScoreService
{
    /** Well-known disposable/temporary-inbox domains. Not exhaustive by design. */
    private const DISPOSABLE_DOMAINS = [
        'mailinator.com', 'guerrillamail.com', 'guerrillamail.info', '10minutemail.com',
        'tempmail.com', 'temp-mail.org', 'throwawaymail.com', 'yopmail.com',
        'trashmail.com', 'sharklasers.com', 'dispostable.com', 'getnada.com',
        'maildrop.cc', 'fakeinbox.com', 'mailnesia.com', 'mintemail.com',
        'mailcatch.com', 'spamgourmet.com', 'moakt.com', 'emailondeck.com',
    ];

    /** Free/heavily-abused TLDs commonly seen in list-scraping spam. */
    private const SUSPICIOUS_TLDS = ['xyz', 'top', 'click', 'work', 'support', 'loan', 'men', 'gq', 'tk', 'ml', 'cf', 'ga'];

    /** Generic mailbox names unlikely to belong to an individual art-list subscriber. */
    private const ROLE_LOCAL_PARTS = [
        'info', 'admin', 'support', 'webmaster', 'postmaster', 'no-reply', 'noreply',
        'sales', 'contact', 'test', 'abuse', 'marketing', 'newsletter',
    ];

    public function __construct(private readonly EmailSignupRepository $signups)
    {
    }

    /**
     * @return array{probability:int, signals:list<string>}
     */
    public function score(TenantContext $tenant, string $email, ?string $name, ?string $source, ?string $ipAddress): array
    {
        $email = strtolower(trim($email));
        $probability = 0;
        $signals = [];

        $atPos = strrpos($email, '@');
        $localPart = $atPos !== false ? substr($email, 0, $atPos) : $email;
        $domain = $atPos !== false ? substr($email, $atPos + 1) : '';

        if ($domain !== '' && in_array($domain, self::DISPOSABLE_DOMAINS, true)) {
            $probability += 50;
            $signals[] = 'disposable_domain';
        }

        $tld = $this->tld($domain);
        if ($tld !== '' && in_array($tld, self::SUSPICIOUS_TLDS, true)) {
            $probability += 20;
            $signals[] = 'suspicious_tld';
        }

        if (in_array($localPart, self::ROLE_LOCAL_PARTS, true)) {
            $probability += 15;
            $signals[] = 'role_address';
        }

        if ($this->looksAutoGenerated($localPart)) {
            $probability += 20;
            $signals[] = 'random_local_part';
        }

        if (trim((string) $name) === '' && trim((string) $source) === '') {
            $probability += 10;
            $signals[] = 'no_name_or_source';
        }

        $ipAddress = trim((string) $ipAddress);
        if ($ipAddress !== '' && $this->signups->recentSignupCountForIp($tenant, $ipAddress, 60) >= 3) {
            $probability += 25;
            $signals[] = 'ip_velocity';
        }

        return [
            'probability' => min(100, $probability),
            'signals' => $signals,
        ];
    }

    private function tld(string $domain): string
    {
        $lastDot = strrpos($domain, '.');
        return $lastDot !== false ? substr($domain, $lastDot + 1) : '';
    }

    /**
     * Flags local parts that look machine-generated: a long digit run, or a
     * long consonant-heavy string with almost no vowels (e.g. "xkqbz7f4h2").
     */
    private function looksAutoGenerated(string $localPart): bool
    {
        if ($localPart === '') {
            return false;
        }

        if (preg_match('/\d{4,}/', $localPart) === 1) {
            return true;
        }

        $letters = preg_replace('/[^a-z]/', '', $localPart) ?? '';
        if (strlen($letters) >= 8) {
            $vowelCount = preg_match_all('/[aeiou]/', $letters);
            if ($vowelCount / strlen($letters) < 0.15) {
                return true;
            }
        }

        return false;
    }
}

// End of file.
